/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class iouring_IOuringSetup */

#ifndef _Included_iouring_IOuringSetup
#define _Included_iouring_IOuringSetup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     iouring_IOuringSetup
 * Method:    ioUringQueueInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_iouring_IOuringSetup_ioUringQueueInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
