/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class iouring_IOuringNativeBindings */

#ifndef _Included_iouring_IOuringNativeBindings
#define _Included_iouring_IOuringNativeBindings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     iouring_IOuringNativeBindings
 * Method:    ioUringQueueInit
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_iouring_IOuringNativeBindings_ioUringQueueInit
//  (JNIEnv *, jobject);

/*
 * Class:     iouring_IOuringNativeBindings
 * Method:    ioUringQueueInitParams
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_iouring_IOuringNativeBindings_ioUringQueueInitParams
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
